GET http://localhost:5000/tasks/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ3NjJmYmI4LTllYjktNDc2Zi1iMWJiLTE1ZGQ4ODZjNGMwNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJkYW1pYW5nb3JlbnNraUBnbWFpbC5jb20iLCJleHAiOjE3NDc1NTY0OTh9.tf4Wefv1i4aoARU4P4H_EQAb-3nbqPX6eh_RuF055ac
Content-Type: application/json